BEGIN TRANSACTION;

CREATE TABLE users (
    id serial NOT NULL PRIMARY KEY, 
    name VARCHAR ( 100 ) NOT NULL, 
    email TEXT UNIQUE NOT NULL,
    entries BIGINT DEFAULT 0,
    joined TIMESTAMP NOT NULL
);

COMMIT;